-- MySQL Script generated by MySQL Workbench
-- Tue Apr 22 22:50:04 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cs230_u240217
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cs230_u240217
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cs230_u240217` DEFAULT CHARACTER SET utf8mb4 ;
USE `cs230_u240217` ;

-- -----------------------------------------------------
-- Table `cs230_u240217`.`albums`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs230_u240217`.`albums` (
  `idalbum` INT(11) NOT NULL AUTO_INCREMENT,
  `numberListens` INT(11) NOT NULL DEFAULT 0,
  `name` TEXT NOT NULL,
  `releaseYear` YEAR(4) NOT NULL,
  PRIMARY KEY (`idalbum`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cs230_u240217`.`artists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs230_u240217`.`artists` (
  `idartist` INT(11) NOT NULL AUTO_INCREMENT,
  `name` TEXT NOT NULL,
  `monthlyListeners` INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idartist`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cs230_u240217`.`albums_artists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs230_u240217`.`albums_artists` (
  `idalbum` INT(11) NOT NULL,
  `idartist` INT(11) NOT NULL,
  UNIQUE INDEX `albums_artists_unique` (`idalbum` ASC, `idartist` ASC) VISIBLE,
  INDEX `fk_albums_artists_albums1_idx` (`idalbum` ASC) VISIBLE,
  INDEX `fk_albums_artists_artists1_idx` (`idartist` ASC) VISIBLE,
  CONSTRAINT `fk_albums_artists_albums1`
    FOREIGN KEY (`idalbum`)
    REFERENCES `cs230_u240217`.`albums` (`idalbum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_albums_artists_artists1`
    FOREIGN KEY (`idartist`)
    REFERENCES `cs230_u240217`.`artists` (`idartist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cs230_u240217`.`songs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs230_u240217`.`songs` (
  `idsong` INT(11) NOT NULL AUTO_INCREMENT,
  `name` TEXT NOT NULL,
  `releaseYear` YEAR(4) NOT NULL,
  `idArtistWriter` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idsong`),
  INDEX `fk_songs_artists_idx` (`idArtistWriter` ASC) VISIBLE,
  CONSTRAINT `fk_songs_artists`
    FOREIGN KEY (`idArtistWriter`)
    REFERENCES `cs230_u240217`.`artists` (`idartist`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 179
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cs230_u240217`.`albums_songs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs230_u240217`.`albums_songs` (
  `idalbum` INT(11) NOT NULL,
  `idsong` INT(11) NOT NULL,
  UNIQUE INDEX `albums_songs_unique` (`idalbum` ASC, `idsong` ASC) VISIBLE,
  INDEX `fk_albums_songs_albums1_idx` (`idalbum` ASC) VISIBLE,
  INDEX `fk_albums_songs_songs1_idx` (`idsong` ASC) VISIBLE,
  CONSTRAINT `fk_albums_songs_albums1`
    FOREIGN KEY (`idalbum`)
    REFERENCES `cs230_u240217`.`albums` (`idalbum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_albums_songs_songs1`
    FOREIGN KEY (`idsong`)
    REFERENCES `cs230_u240217`.`songs` (`idsong`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cs230_u240217`.`genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs230_u240217`.`genres` (
  `idgenre` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idgenre`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cs230_u240217`.`artists_genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs230_u240217`.`artists_genres` (
  `idgenre` INT(11) NOT NULL,
  `idartist` INT(11) NOT NULL,
  UNIQUE INDEX `artists_genres_unique` (`idgenre` ASC, `idartist` ASC) VISIBLE,
  INDEX `fk_artists_genres_genres1_idx` (`idgenre` ASC) VISIBLE,
  INDEX `fk_artists_genres_artists1_idx` (`idartist` ASC) VISIBLE,
  CONSTRAINT `fk_artists_genres_artists1`
    FOREIGN KEY (`idartist`)
    REFERENCES `cs230_u240217`.`artists` (`idartist`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_artists_genres_genres1`
    FOREIGN KEY (`idgenre`)
    REFERENCES `cs230_u240217`.`genres` (`idgenre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cs230_u240217`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs230_u240217`.`client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `name` TEXT NOT NULL,
  `email` TEXT NOT NULL,
  `phoneNumber` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idClient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs230_u240217`.`therapist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs230_u240217`.`therapist` (
  `idTherapist` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `name` TEXT NOT NULL,
  `email` TEXT NOT NULL,
  `location` TEXT NOT NULL,
  `yearsOfPractice` TINYINT NOT NULL,
  `availability` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idTherapist`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs230_u240217`.`session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs230_u240217`.`session` (
  `idSession` INT NOT NULL AUTO_INCREMENT,
  `idClient` INT NOT NULL,
  `idTherapist` INT NOT NULL,
  `date` DATE NOT NULL,
  `length` INT NOT NULL,
  `frequency` ENUM("WEEKLY", "MONTHLY") NOT NULL DEFAULT 'WEEKLY',
  `notes` TEXT NULL,
  INDEX `fk_table1_client1_idx` (`idClient` ASC) VISIBLE,
  INDEX `fk_table1_therapist1_idx` (`idTherapist` ASC) VISIBLE,
  PRIMARY KEY (`idSession`),
  CONSTRAINT `fk_table1_client1`
    FOREIGN KEY (`idClient`)
    REFERENCES `cs230_u240217`.`client` (`idClient`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_table1_therapist1`
    FOREIGN KEY (`idTherapist`)
    REFERENCES `cs230_u240217`.`therapist` (`idTherapist`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs230_u240217`.`notes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs230_u240217`.`notes` (
  `idnotes` INT NOT NULL AUTO_INCREMENT,
  `idSession` INT NOT NULL,
  `note` TEXT NOT NULL,
  PRIMARY KEY (`idnotes`),
  INDEX `fk_notes_session1_idx` (`idSession` ASC) VISIBLE,
  CONSTRAINT `fk_notes_session1`
    FOREIGN KEY (`idSession`)
    REFERENCES `cs230_u240217`.`session` (`idSession`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs230_u240217`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs230_u240217`.`Users` (
  `idUsers` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `passwordHash` TEXT NOT NULL,
  PRIMARY KEY (`idUsers`),
  UNIQUE INDEX `idUsers_UNIQUE` (`idUsers` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs230_u240217`.`TravelLogs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs230_u240217`.`TravelLogs` (
  `idTravelLogs` INT NOT NULL AUTO_INCREMENT,
  `idUsers` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `startDate` DATE NOT NULL,
  `endDate` DATE NOT NULL,
  `postDate` DATE NOT NULL DEFAULT NOW(),
  `description` TEXT NULL,
  PRIMARY KEY (`idTravelLogs`),
  INDEX `fk_TravelLogs_Users1_idx` (`idUsers` ASC) VISIBLE,
  CONSTRAINT `fk_TravelLogs_Users1`
    FOREIGN KEY (`idUsers`)
    REFERENCES `cs230_u240217`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs230_u240217`.`Tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs230_u240217`.`Tags` (
  `idTags` INT NOT NULL AUTO_INCREMENT,
  `tag` VARCHAR(45) BINARY NOT NULL,
  PRIMARY KEY (`idTags`),
  UNIQUE INDEX `tag_UNIQUE` (`tag` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs230_u240217`.`TravelLogs_has_Tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs230_u240217`.`TravelLogs_has_Tags` (
  `idTravelLogs` INT NOT NULL,
  `idTags` INT NOT NULL,
  PRIMARY KEY (`idTravelLogs`, `idTags`),
  INDEX `fk_TravelLogs_has_Tags_Tags1_idx` (`idTags` ASC) VISIBLE,
  INDEX `fk_TravelLogs_has_Tags_TravelLogs1_idx` (`idTravelLogs` ASC) VISIBLE,
  CONSTRAINT `fk_TravelLogs_has_Tags_TravelLogs1`
    FOREIGN KEY (`idTravelLogs`)
    REFERENCES `cs230_u240217`.`TravelLogs` (`idTravelLogs`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_TravelLogs_has_Tags_Tags1`
    FOREIGN KEY (`idTags`)
    REFERENCES `cs230_u240217`.`Tags` (`idTags`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs230_u240217`.`JourneyPlans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs230_u240217`.`JourneyPlans` (
  `idJourneyPlans` INT NOT NULL AUTO_INCREMENT,
  `idUsers` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `startDate` DATE NOT NULL,
  `endDate` DATE NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`idJourneyPlans`),
  INDEX `fk_JourneyPlan_Users1_idx` (`idUsers` ASC) VISIBLE,
  CONSTRAINT `fk_JourneyPlan_Users1`
    FOREIGN KEY (`idUsers`)
    REFERENCES `cs230_u240217`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs230_u240217`.`Locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs230_u240217`.`Locations` (
  `idLocations` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLocations`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs230_u240217`.`Activities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs230_u240217`.`Activities` (
  `idActivities` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idActivities`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs230_u240217`.`JourneyPlan_has_Locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs230_u240217`.`JourneyPlan_has_Locations` (
  `idJourneyPlans` INT NOT NULL,
  `idLocations` INT NOT NULL,
  PRIMARY KEY (`idJourneyPlans`, `idLocations`),
  INDEX `fk_JourneyPlan_has_Locations_Locations1_idx` (`idLocations` ASC) VISIBLE,
  CONSTRAINT `fk_JourneyPlan_has_Locations_JourneyPlan1`
    FOREIGN KEY (`idJourneyPlans`)
    REFERENCES `cs230_u240217`.`JourneyPlans` (`idJourneyPlans`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_JourneyPlan_has_Locations_Locations1`
    FOREIGN KEY (`idLocations`)
    REFERENCES `cs230_u240217`.`Locations` (`idLocations`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs230_u240217`.`JourneyPlan_has_Activities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs230_u240217`.`JourneyPlan_has_Activities` (
  `idJourneyPlans` INT NOT NULL,
  `idActivities` INT NOT NULL,
  PRIMARY KEY (`idJourneyPlans`, `idActivities`),
  INDEX `fk_JourneyPlan_has_Activities_Activities1_idx` (`idActivities` ASC) VISIBLE,
  CONSTRAINT `fk_JourneyPlan_has_Activities_JourneyPlan1`
    FOREIGN KEY (`idJourneyPlans`)
    REFERENCES `cs230_u240217`.`JourneyPlans` (`idJourneyPlans`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_JourneyPlan_has_Activities_Activities1`
    FOREIGN KEY (`idActivities`)
    REFERENCES `cs230_u240217`.`Activities` (`idActivities`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
